version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  aws-s3: circleci/aws-s3@1.0.11
  aws-cli: circleci/aws-cli@2.0.0
  node: circleci/node@4.2.0

dev_only: &dev_only
  filters:
    branches:
      only: dev

master_only: &master_only
  filters:
    branches:
      only: master

run_tests: &run_tests
  <<: *dev_only
  start: npm run test && npm run start:ci
  wait-on: 'http://localhost:3000'
  record: true

push: &push
  docker:
    - image: 'cimg/python:3.6'
  parameters:
    push_to:
      type: string
      default: 's3://trailmaps-link'
  steps:
    - attach_workspace:
        at: build
    - aws-s3/copy:
        from: build/build/
        arguments: "--recursive"
        to: "<< parameters.push_to >>"

jobs:
  build:
    docker:
      - image: cimg/node:16.14.0
    parameters:
      build_command:
        type: string
        default: ''
    steps:
      - checkout
      - run: npm install
      - run: CI=false << parameters.build_command >> # prevent fail due to eslint
      - persist_to_workspace:
          root: .
          paths:
            - build
  push:
    <<: *push
  invalidate_cache:
    executor: aws-cli/default
    parameters:
      distribution_id:
        type: string
        default: ''
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run: aws cloudfront create-invalidation --distribution-id << parameters.distribution_id >> --paths /\*

workflows:
  deploy_dev:
    jobs:
      - cypress/run:
          <<: *dev_only
          <<: *run_tests
          name: test
      - build:
          <<: *dev_only
          requires:
            - test
          build_command: npm run build_dev
      - invalidate_cache:
          <<: *dev_only
          requires:
            - build
          distribution_id: E312A5GIQSDGC2
      - push:
          <<: *dev_only
          requires:
            - build
          push_to: 's3://trailmaps-link'

  deploy_prod:
    jobs:
#      - cypress/run:
#          <<: *master_only
#          <<: *run_tests
#          name: test
      - build:
          <<: *master_only
#          requires:
#            - test
          build_command: npm run build_prod
      - invalidate_cache:
          <<: *master_only
          requires:
            - build
          distribution_id: E1WUZVCMER8SAR
      - push:
          <<: *master_only
          requires:
            - build
          push_to: 's3://trailmaps-site'
