# to use orbs, must use version >= 2.1
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  aws-s3: circleci/aws-s3@1.0.11
  node: circleci/node@4.2.0

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: CI=false npm run build # prevent fail due to eslint
      - persist_to_workspace:
          root: .
          paths:
            - build
  push:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - attach_workspace:
          at: build
      - aws-s3/sync:
          from: build/*
          to: "s3://trailmaps-link"

workflows:
  build_and_push:
    jobs:
      - build
      - push:
          requires:
            - build
  test:
    jobs:
      - cypress/run:
          filters: # using regex filters requires the entire branch to match
            branches:
              only: # only branches matching the below regex filters will run
                - dev
          start: npm run start:ci
          wait-on: "http://localhost:3000"
          record: true
